# Generated by Django 3.0.4 on 2020-04-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200419_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('R', 'rent'), ('S', 'sale')], max_length=10),
        ),
    ]
