# Generated by Django 3.0.4 on 2020-04-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200419_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('S', 'sale'), ('R', 'rent')], max_length=10),
        ),
    ]
