# Generated by Django 3.0.4 on 2020-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200419_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='garages_nmuber',
            new_name='garages_number',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('S', 'sale'), ('R', 'rent')], max_length=10),
        ),
    ]
