# Generated by Django 3.0.4 on 2020-04-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20200419_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=10),
        ),
    ]
