# Generated by Django 3.0.4 on 2020-04-22 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20200422_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reserver',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Property'),
        ),
    ]
