# Generated by Django 3.0.4 on 2020-04-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20200422_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_type',
            field=models.CharField(choices=[('Total Amount', 'Total Amount'), ('per month', 'per month')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], max_length=10),
        ),
    ]
