# Generated by Django 3.0.6 on 2020-05-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20200422_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=10),
        ),
    ]
